/**
 * Curated app icon catalogue. Import from here instead of the Hugeicons
 * package in screens/components so the app stays visually consistent.
 */
export {
  Add01Icon as AddIcon,
  ArrowDown01Icon as ChevronDownIcon,
  ArrowLeft01Icon as BackIcon,
  ArrowRight01Icon as ForwardIcon,
  ArrowUp01Icon as ChevronUpIcon,
  Calendar03Icon as CalendarIcon,
  Cancel01Icon as CloseIcon,
  Tick02Icon as CheckIcon,
  Clock01Icon as ClockIcon,
  Download01Icon as DownloadIcon,
  HelpCircleIcon as HelpIcon,
  Invoice01Icon as InvoiceIcon,
  LanguageCircleIcon as LanguageIcon,
  Logout01Icon as LogoutIcon,
  MapPinIcon as MapPinIcon,
  Notification01Icon as AlertsIcon,
  PencilEdit01Icon as EditIcon,
  GridViewIcon as ProductsIcon,
  Home01Icon as HomeIcon,
  LockIcon as LockIcon,
  Location01Icon as LocationIcon,
  Settings02Icon as SettingsIcon,
  Shield01Icon as ShieldIcon,
  MinusSignIcon as MinusIcon,
  Notification03Icon as NotificationIcon,
  Search01Icon as SearchIcon,
  ShoppingCart01Icon as CartIcon,
  TelephoneIcon as PhoneIcon,
  TruckIcon as TruckIcon,
  UserIcon as ProfileIcon,
  Wallet01Icon as WalletIcon,
} from "@hugeicons/core-free-icons";
